// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv_uLWOR6m46qM0QoSr0nWuR7OoxAGL0g',
    appId: '1:578295022844:web:1f35d320226306ef938379',
    messagingSenderId: '578295022844',
    projectId: 'wisp-f2551',
    authDomain: 'wisp-f2551.firebaseapp.com',
    storageBucket: 'wisp-f2551.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA03XheWf4KEuR4wFVsXUL_Fb_YWaVppVU',
    appId: '1:578295022844:android:b5941139bea922f4938379',
    messagingSenderId: '578295022844',
    projectId: 'wisp-f2551',
    storageBucket: 'wisp-f2551.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD12MMqmp_LAikZAx0N6W6B-b85GIEW1UI',
    appId: '1:578295022844:ios:05336c17ae9f7581938379',
    messagingSenderId: '578295022844',
    projectId: 'wisp-f2551',
    storageBucket: 'wisp-f2551.firebasestorage.app',
    iosBundleId: 'com.example.appWisp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD12MMqmp_LAikZAx0N6W6B-b85GIEW1UI',
    appId: '1:578295022844:ios:05336c17ae9f7581938379',
    messagingSenderId: '578295022844',
    projectId: 'wisp-f2551',
    storageBucket: 'wisp-f2551.firebasestorage.app',
    iosBundleId: 'com.example.appWisp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv_uLWOR6m46qM0QoSr0nWuR7OoxAGL0g',
    appId: '1:578295022844:web:917b94c8aa27871d938379',
    messagingSenderId: '578295022844',
    projectId: 'wisp-f2551',
    authDomain: 'wisp-f2551.firebaseapp.com',
    storageBucket: 'wisp-f2551.firebasestorage.app',
  );
}
